<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

	<form class="row col-auto m-2 mt-5 bg-warning border border-dark" method="POST" action="sessions_home.php">

		<div class="w-50 my-3">
			<input type="text" class="form-control" id="inputnumber" placeholder="Enter value" name="input_1" value = "<?php echo $input1; ?>">
		</div>


		<div class="w-50 my-3">
			<input type="text" class="form-control" id="inputnumber" placeholder="Enter value" name="input_2" value = "<?php echo $input2; ?>">
		</div>

		<div class="w-100 mb-3">
			<input class="form-control" type="text" aria-label="" readonly placeholder="Result output here" name="output_1" value = "<?php echo $output1; ?>">
		</div>


		<div class="row m-0">

			<button type="submit" class="btn btn-secondary mb-3 w-25" name="click" value="add">Add</button>


			<button type="submit" class="btn btn-secondary mb-3 w-25" name="click" value="subtract">Subtract</button>


			<button type="submit" class="btn btn-secondary mb-3 w-25" name="click" value="multiply">Multiply</button>


			<button type="submit" class="btn btn-secondary mb-3 w-25" name="click" value="divide">Divide</button>


			<button type="submit" class="btn btn-secondary mb-3 w-25" name="click" value="square">Square</button>

			<button type="submit" class="btn btn-danger mb-3 w-25" name="click" value="reset">Reset</button>


			<textarea class="form-control mb-3" placeholder="All history records will be displayed here" id="floatingTextarea" name="output_2"></textarea>

		</div>			

	</form>

</body>
</html>