<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<style>
	table {
		font-family: arial, sans-serif;
		border-collapse: collapse;
		width: 100%;
	}

	td, th {
		border: 1px solid #dddddd;
		text-align: left;
		padding: 8px;
	}

	tr:nth-child(even) {
		background-color: #dddddd;
	}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>title</th>
				<th>author</th>
				<th>year</th>
				<th>genre</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($library as $value): ?>
			<tr>
				<td><?php echo $value['title']; ?></td>
				<td><?php echo $value['author']; ?></td>
				<td><?php echo $value['year']; ?></td>
				<td><?php echo $value['genre']; ?></td>
			</tr>
			<?php endforeach; ?>
			<tr>
				<td colspan="2"></td>
				<td><?php echo $averageYear; ?></td>
			</tr>
		</tbody>
	</table>

</body>
</html>

